// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAgzFf31UqSspjVtPvGdeE7w2M13T7nVrg',
    appId: '1:552195318590:web:f80bf2aef1336f381dc26f',
    messagingSenderId: '552195318590',
    projectId: 'skycast-db918',
    authDomain: 'skycast-db918.firebaseapp.com',
    storageBucket: 'skycast-db918.firebasestorage.app',
    measurementId: 'G-T6QFEXSTYK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8ZnHg87Y8vdZUGeTptjPWeHR6qps9jJE',
    appId: '1:552195318590:android:411bb6992d43a1621dc26f',
    messagingSenderId: '552195318590',
    projectId: 'skycast-db918',
    storageBucket: 'skycast-db918.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-Gvd1qWulT2-mymWXMxE-ayW2rodDMXc',
    appId: '1:552195318590:ios:a69806ef6f93d3de1dc26f',
    messagingSenderId: '552195318590',
    projectId: 'skycast-db918',
    storageBucket: 'skycast-db918.firebasestorage.app',
    iosBundleId: 'com.example.skycastApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-Gvd1qWulT2-mymWXMxE-ayW2rodDMXc',
    appId: '1:552195318590:ios:a69806ef6f93d3de1dc26f',
    messagingSenderId: '552195318590',
    projectId: 'skycast-db918',
    storageBucket: 'skycast-db918.firebasestorage.app',
    iosBundleId: 'com.example.skycastApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAgzFf31UqSspjVtPvGdeE7w2M13T7nVrg',
    appId: '1:552195318590:web:cb611b7b61f8c8001dc26f',
    messagingSenderId: '552195318590',
    projectId: 'skycast-db918',
    authDomain: 'skycast-db918.firebaseapp.com',
    storageBucket: 'skycast-db918.firebasestorage.app',
    measurementId: 'G-YSN5KKPLM2',
  );
}
